#!/bin/bash
# /etc/init.d/boli

### BEGIN INIT INFO
# Provides:          boli
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a servo
### END INIT INFO


case "$1" in 
    start)
        echo "Starting Bolirana"
        /usr/local/python /home/sebastian/bolirana/bolirana12.py
        ;;
    stop)
        echo "Stopping servoblaster"
        killall boli
        ;;
    *)
        echo "Usage: /etc/init.d/servod start|stop"
        exit 1
        ;;
esac

exit 0
